### ISSUE TITLE
Allow SDK usage for non-root users

### ISSUE THREAD

**Issue by ajkxyz** [DigitalMediaProfessionals/dv-sdk#3]
It is not good to require for applications to be executed under root, so I suggest:

1. Create group `dmp`.
2. Change group of `/dev/ion` `/dev/dv_conv` `/dev/dv_fc` to `dmp` and permissions to `0660`.
3. Add group `dmp` to `ubuntu` user.

**Comment by ZongHong-Lyu** [comment]
Done
